# Generated by Django 4.1 on 2022-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(blank=True, max_length=11, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=64, null=True)),
                ('nome', models.CharField(blank=True, max_length=11, null=True)),
                ('unidade', models.CharField(blank=True, max_length=64, null=True)),
                ('marca', models.CharField(blank=True, max_length=64, null=True)),
                ('modelo', models.CharField(blank=True, max_length=64, null=True)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estoque', models.CharField(blank=True, max_length=64, null=True)),
                ('grupo', models.CharField(blank=True, max_length=64, null=True)),
                ('descricao', models.CharField(blank=True, max_length=64, null=True)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('fornecedor', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
