# Generated by Django 4.1 on 2022-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='mobilizacao',
            field=models.CharField(blank=True, choices=[('REP', 'Reposicao'), ('VND', 'Venda'), ('GNT', 'Garantia')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='unidade',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PT', 'Pacote'), ('KT', 'Kit'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('MT', 'Metro')], max_length=64, null=True),
        ),
    ]
