# Generated by Django 4.1 on 2022-08-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produtos_mobilizacao_alter_produtos_codigo_barras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacao', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG/CPF/CNPJ')),
                ('nome', models.CharField(max_length=64)),
                ('apelido', models.CharField(blank=True, max_length=64, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(blank=True, max_length=64, null=True)),
                ('endereco', models.CharField(blank=True, max_length=64, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=64, null=True)),
                ('bairro', models.CharField(blank=True, max_length=64, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=32, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=32, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('contato', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('observacao', models.TextField(blank=True, max_length=255, null=True)),
                ('tipo_cliente', models.BooleanField(blank=True, default=False, null=True)),
                ('tipo_fornecedor', models.BooleanField(blank=True, default=False, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='mobilizacao',
            field=models.CharField(blank=True, choices=[('REP', 'Reposicao'), ('VND', 'Venda'), ('GNT', 'Garantia')], max_length=3, null=True),
        ),
    ]
