# Generated by Django 4.1 on 2022-08-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_alter_produtos_mobilizacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
