# Generated by Django 4.1 on 2022-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_fornecedor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É Fornecedor'),
        ),
    ]
