# Generated by Django 4.1 on 2022-08-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chamados'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='OrdensDeServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento', models.CharField(blank=True, max_length=64, null=True, verbose_name='Equipamento')),
                ('numero_serie', models.CharField(blank=True, max_length=64, null=True, verbose_name='N.Serie')),
                ('tecnico', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tecnico')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chamados')),
                ('produto', models.ManyToManyField(blank=True, null=True, to='api.produtos')),
            ],
        ),
    ]
