# Generated by Django 4.1 on 2022-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ordensdeservico_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='numero_identificacao',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='RG/CPF/CNPJ'),
        ),
    ]
