# Generated by Django 4.1 on 2022-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_clientes_numero_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='contato_chamado',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='telefone_chamado',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
