# Generated by Django 4.1 on 2022-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chamados_contato_chamado_chamados_telefone_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
