# Generated by Django 4.1 on 2022-09-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_produtos_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
