# Generated by Django 4.1 on 2022-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pedidodevenda_pedidoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodevenda',
            name='contato_venda',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pedidodevenda',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodevenda',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodevenda',
            name='telefone_venda',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
