# Generated by Django 4.1 on 2022-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_ordensdeservico_peca_ordensdeservico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='status_os',
            field=models.CharField(blank=True, choices=[('1', 'Pendente'), ('2', 'Aberta'), ('3', 'Encerrada')], max_length=2, null=True),
        ),
    ]
