# Generated by Django 4.1 on 2022-10-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_chamados_status_os_chamados_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pendente'), ('2', 'Manutencao'), ('3', 'Finalizada'), ('4', 'Reprovado')], max_length=2, null=True),
        ),
    ]
