# Generated by Django 4.1 on 2022-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_ordensdeservico_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='status2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
