# Generated by Django 4.1 on 2022-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_chamados_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensdeservico',
            name='status2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
