# Generated by Django 4.1 on 2022-10-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_ordensdeservico_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='logo_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='status2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordensdeservico',
            name='status2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
