# Generated by Django 4.1 on 2022-09-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacao', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG/CPF/CNPJ')),
                ('nome', models.CharField(max_length=64)),
                ('apelido', models.CharField(blank=True, max_length=64, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(blank=True, max_length=64, null=True)),
                ('endereco', models.CharField(blank=True, max_length=64, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=64, null=True)),
                ('bairro', models.CharField(blank=True, max_length=64, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=32, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=32, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('contato', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('observacao', models.TextField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
