# Generated by Django 4.1 on 2022-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
